version: "3.9"
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    privileged: true
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Berlin # Replace with your actual time zone if different
    volumes:
      - /home/euberto/containers/hass:/config
      - /run/dbus:/run/dbus:ro