  services:
    homer:
      image: b4bz/homer
      container_name: homer
      volumes:
        - /Users/euberto/Desktop/Homer:/www/assets
      ports:
        - 8092:8080
      user: 503:20 # default
      environment:
        - INIT_ASSETS=1 # default