version: '3'
services:
  postgresql:
    image: postgres:16
    container_name: keycloak_postgresql
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: SUPERsecret
    volumes:
      - '/home/euberto/containers/keycloak/postgresql_data:/var/lib/postgresql/data'
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    container_name: keycloak
    restart: always
    command: start
    depends_on:
      - postgresql
    environment:
      KC_PROXY_ADDRESS_FORWARDING: "true"
      KC_HTTP_ENABLED: "true"
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: SUPERsecret
      KC_DB_URL_HOST: postgresql
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KEYCLOAK_ADMIN: euberto
      KEYCLOAK_ADMIN_PASSWORD: keycloak
    ports:
      - "8080:8080"  # Exposes Keycloak's default HTTP port
    volumes:
      - '/home/euberto/containers/keycloak/keycloak_data:/opt/keycloak/data'
    networks:
      - keycloak_network

networks:
  keycloak_network:
    driver: bridge