version: "3.9"
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.5
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: start-dev