services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    restart: unless-stopped
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - /home/euberto/containers/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/euberto/containers/nginx/certs:/etc/nginx/certs:ro    # SSL certificates
      - /home/euberto/containers/nginx/logs:/var/log/nginx          # Logs
      - /home/euberto/containers/nginx/html:/usr/share/nginx/html   # Static files (optional)
    networks:
      - proxy_network

networks:
  proxy_network:
    driver: bridge