services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/euberto/containers/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/euberto/containers/nginx/certs:/etc/nginx/certs:ro
      - /home/euberto/containers/nginx/logs:/var/log/nginx
      - /home/euberto/containers/nginx/html:/usr/share/nginx/html
    networks:
      - paperless_default

networks:
  paperless_default:
    external: true


    # Test if everything lands on Pi
