services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" # Expose Grafana on port 3000
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always

volumes:
  grafana_data: # Persistent data storage for Grafana