services:
  broker:
    image: docker.io/library/redis:7
    container_name: paperless_broker
    restart: unless-stopped
    volumes:
      - /home/euberto/containers/paperless/redisdata:/data  # Redis data stored locally

  db:
    image: docker.io/library/postgres:16
    container_name: paperless_DB
    restart: unless-stopped
    volumes:
      - /home/euberto/containers/paperless/pgdata:/var/lib/postgresql/data  # PostgreSQL data stored locally
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8020:8000"
    volumes:
      - /home/euberto/containers/paperless/data:/usr/src/paperless/data   # Local storage for paperless data
      - /home/euberto/containers/paperless/media:/usr/src/paperless/media  # Local storage for media files
      - /home/euberto/containers/paperless/export:/usr/src/paperless/export  # Local storage for exports
      - /home/euberto/containers/paperless/consume:/usr/src/paperless/consume  # Local storage for consumed files
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_IGNORE_SIGNATURES: "true"
      USERMAP_UID: 1000  # Set this to your host user ID on the Pi
      USERMAP_GID: 1000  # Set this to your host group ID on the Pi