version: '3.8'

services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    ports:
      - "8091:80"  # Map local port 8091 to container's port 80
    volumes:
      - /home/euberto/containers/FreshRSS:/var/www/FreshRSS/data  # Mount local volume to container
    environment:
      - TZ=Europe/Berlin  # Set timezone as needed
    restart: unless-stopped
