  services:
    homer:
      image: b4bz/homer
      container_name: homer
      volumes:
        - /home/euberto/containers/homer:/www/assets
      ports:
        - 8092:8080
      user: "503:20" # default
      environment:
        - INIT_ASSETS=1 # default