name: Lint Ansible Playbook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Ansible Playbook
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4  # Fetch the repository files

      - name: Debug File Location
        run: ls -R ansible/  # Confirm the file exists in the expected directory

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Ansible and Ansible-Lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Run Ansible Lint
        run: ansible-lint ansible/ansible-testpi.yaml
